    <header class="header">
        <div class="container">
            <img class="hamburguer" id="hamburguer" src="/img/menu.png" alt="">
            <a href="/localizacao">
                <img class="logo" src="/img/iconeLogo.png" height="50px" width="70px" alt="">
            </a>
            <div class="header__notification">
                <div class="notification__ball"></div>
                <a href="/notifications.php">
                <img src="/img/bell.png" alt="" width="30" class="bell">
                </a>
            </div>
        </div>
    </header>