<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Maria</title>
    <link rel="stylesheet" href="css/profile.css">
    <link rel="stylesheet" href="css/header.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,600,900" rel="stylesheet">
    <script src="js/jquery.min.js"></script>
    <script src="sidemenu/sidemenu.js"></script>
    <link rel="stylesheet" href="sidemenu/sidemenu.css">
    <link rel="stylesheet" href="css/imagemodal.css">
</head>
<body>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MZZWXLM"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div class="modal__out" id="image-modal">
    <div class="modal__box">
        <div class="modal__close" id="close-image-modal">
            <img src="./img/close.png" alt="">
        </div>
        <img src="./img/profile-cover.jpg" alt="" id="modal-img" class="modal__image">

    </div>
</div>
<?php include 'menulat.phtml'; ?>
<?php include 'header.phtml'; ?>
<div class="profile__cover">
</div>

<div class="profile__content">
    <div class="profile__data">
        <div class="profile__cover__mobile">
            <div class="profile__photo">
                <?php if (!empty($_SESSION['userAlbum'])) { ;?>
                        <img src="photos/<?php echo $_SESSION['userAlbum']['name']; ?>" alt="">
                <?php }?>
            </div>
        </div>
</div>
<div style="margin-bottom: 50%;padding: 9%;">
    <h1 class="" style="color: #429DC4;">
        Somos uma plataforma de conexão para as mulheres que vão para o mesmo local que você. Assim, incentivando a sororidade e facilitamos a mobilidade entre nós!
    </h1>
</div>
<div id="newdate">
    <a href="selectModal"><img src="img/search_.png" alt=""></a>
</div>

<script src="profile.js"></script>
</body>
</html>