<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Me Separei</title>
    <link rel="stylesheet" href="/css/dateinfos.css">
    <link rel="stylesheet" href="/css/header.css">
  
    <link rel="stylesheet" href="css/modal.css">
    <link rel="stylesheet" href="css/slick.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,600,900" rel="stylesheet">
    <script src="/js/jquery.min.js"></script>
    <script src="/sidemenu/sidemenu.js"></script>
    <link rel="stylesheet" href="/sidemenu/sidemenu.css">
</head>
<body>
<body>
<?php include 'menulat.phtml'; ?>
<?php include 'header.phtml'; ?>
    <form action="selectModal" id="cadastro-form" class="modal__form">                
      <input name="nome" type="text" placeholder="Ponto A" class="modal__input">    
      <input name="user" type="text" placeholder="Ponto B" class="modal__input">      
      <input style="width:100%;"class="modal__submit" type="submit" value="Buscar">
    </form>
    <script src="/js/profile.js"></script>
</body>
</html>

