
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Me Separei</title>
    <link rel="stylesheet" href="/css/dateinfos.css">
    <link rel="stylesheet" href="/css/header.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,600,900" rel="stylesheet">
    <script src="/js/jquery.min.js"></script>
    <script src="/sidemenu/sidemenu.js"></script>
    <link rel="stylesheet" href="/sidemenu/sidemenu.css">
</head>
<body>
<body>
<?php include 'menulat.pphp'; ?>
<?php include 'header.pphp'; ?>
    <div class="profile__cover">
    </div>

    <div class="profile__content">
        <div class="profile__data">
            <div class="profile__cover__mobile">

                <div class="profile__photo">                  
                  <img src="./photos/<?php echo $useravatar_date['name']; ?>" alt="">
                </div>
                
                <div class="profile__info">
                <?php echo $userdateinfo['user']; ?>, <?php echo $userdateinfo['age']; ?> anos<br>
                    <span class="city">
                    <?php echo $date_info['city']; ?>, <?php echo $date_info['state']; ?>
                    </span>
                </div>
            </div>
            <form action="<?php echo $buttom_link; ?>" method="post">
            <input type="hidden" id="" name="dateid" value="<?php echo $date_info['id']; ?>">
            <input type="hidden" id="" name="creator_id" value="<?php echo $date_info_creator_id; ?>">
            <button tyoe="submit" id="follow" class="btn">
                <?php echo $buttom; ?>
            </button>
            </form>
            <div class="profile__text">
            <h4>Um pouco de mim</h4><br>
            <?php echo $date_info_creator; ?>
            </div>
        </div>
        
        <div id="map" style="width:100%;height:400px;"></div>
        <div>
          <a href="/uber" class="btn small">Selecionar tipo de Uber</a>
        </div>
    </div>
    <script src="/js/profile.js"></script>
    <script>
      window.onload = function() {
          var latlng = new google.maps.LatLng(-30.0635642, -51.173968);
          var map = new google.maps.Map(document.getElementById('map'), {
              center: latlng,
              zoom: 11,
              mapTypeId: google.maps.MapTypeId.ROADMAP
          });
          var marker = new google.maps.Marker({
              position: latlng,
              map: map,
              title: 'Set lat/lon values for this property',
              draggable: true
          });
          google.maps.event.addListener(marker, 'dragend', function(a) {
              console.log(a);
              var div = document.createElement('div');
              div.innerHTML = a.latLng.lat().toFixed(4) + ', ' + a.latLng.lng().toFixed(4);
              document.getElementsByTagName('body')[0].appendChild(div);
          });
      };
    </script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6bSohJwJW-eXkHq_w7qTnFB8Y4K0ZVks&callback=myMap"></script>
</body>
</html>






