<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Maria</title>
    <link rel="stylesheet" href="/css/dateinfos.css">
    <link rel="stylesheet" href="/css/header.css">
  
    <link rel="stylesheet" href="/css/modal.css">
    <link rel="stylesheet" href="/css/slick.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,600,900" rel="stylesheet">
    <script src="/js/jquery.min.js"></script>
    <script src="/sidemenu/sidemenu.js"></script>
    <link rel="stylesheet" href="/sidemenu/sidemenu.css">
</head>
<body>
<body>
<?php include 'menulat.phtml'; ?>
<?php include 'header.phtml'; ?>
    <h4 style="text-align:center;">Informe seu trajeto</h4>
    <form action="/selectModal" id="trajeto" class="modal__form">                
      <input name="localizacaoa" type="text" placeholder="Ponto A" class="modal__input">    
      <input onfocus="$('#mapa').show();" id="localB" name="localizacaob" type="text" placeholder="Ponto B" class="modal__input">      
      <input style="width:100%;"class="modal__submit" type="submit" value="Buscar">
    </form>
    <img id="mapa" hidden style="" width="400px;"src="/img/maps.png"/>
    <script src="/js/profile.js"></script>
</body>

<script>


</script>
</html>

