<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Maria</title>
    <link rel="stylesheet" href="/css/dateinfos.css">
    <link rel="stylesheet" href="/css/header.css">
  
    <link rel="stylesheet" href="/css/modal.css">
    <link rel="stylesheet" href="/css/slick.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,600,900" rel="stylesheet">
    <script src="/js/jquery.min.js"></script>
    <script src="/sidemenu/sidemenu.js"></script>
    <link rel="stylesheet" href="/sidemenu/sidemenu.css">
</head>
<body>
<body>
<?php include 'menulat.phtml'; ?>
<?php include 'header.phtml'; ?>
    <a href="/uber/-30,0588/-51,1664/price"><img style="" width="320px;"src="/img/metch.png"/></a>
    <script src="/js/profile.js"></script>
</body>
</html>

