    <div id="sidemenu">
        <div class="menu__top">
            <div id="close-menu" class="menu__close">
                <img src="/img/close.png" alt="">
            </div>
            <div class="menu__title">
                MENU
            </div>
            <ul class="menu__list">
                <li class="menu__item">
                    <a href="newdate.php">
                        Criar Encontro
                    </a>
                </li>
                <li class="menu__item">
                    <a href="mydates.php">
                        Meus Encontros Criados
                    </a>
                </li>
                <li class="menu__item">
                    <a href="finddate.php">
                        Buscar Encontros
                    </a>
                </li>
                <li class="menu__item">
                    <a href="edit_profile">
                        Editar Perfil
                    </a>
                </li>
            </ul>
        </div>

        <div class="menu__bottom">
                <div onclick="logout()" class="menu__logout">
                    Logout
                </div>
            </div>
    </div>