<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Maria</title>
    <link rel="stylesheet" href="/css/dateinfos.css">
    <link rel="stylesheet" href="/css/header.css">
  
    <link rel="stylesheet" href="/css/modal.css">
    <link rel="stylesheet" href="/css/slick.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,600,900" rel="stylesheet">
    <script src="/js/jquery.min.js"></script>
    <script src="/sidemenu/sidemenu.js"></script>
    <link rel="stylesheet" href="/sidemenu/sidemenu.css">
    <style>
    .buttons {
    margin-top: 100px;
}
.btn {
    font-family: 'Roboto', sans-serif;
    font-size: 22px;
    font-weight: 200;
    padding: 10px 28px;
    border-radius: 50px;
    border: none;
    background-image: linear-gradient(-246.79deg, #01060A 0%, #ccc 100%);
    margin: 0 15px;
    cursor: pointer;
    transition: opacity .2s;
    text-decoration: none;

    margin-top: 20px;

}
.btn:hover {
    opacity: .7;
}
    </style>
</head>
<body>
<body>
<?php include 'menulat.phtml'; ?>
<?php include 'header.phtml'; ?>

        <?php 
            for($i = 0; $i < count($produtos->prices); ++$i) {
                echo "<button class='btn' href='/final' style='margin-left:20px;'><b>".$produtos->prices[$i]->display_name."</b> - Valor: ".$produtos->prices[$i]->estimate."</button>";
            } 
        ?>
      <script src="/js/profile.js"></script>
</body>
</html>